# This workflow runs CI tasks for a Node.js project on every push or pull request to the master branch

name: Node.js CI

# Trigger the workflow on push or pull request events targeting the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # Use the latest Ubuntu runner provided by GitHub Actions
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v2

      # Step 2: Set up Node.js environment using version 18
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies with legacy-peer-deps to resolve version conflicts
      - run: npm install --legacy-peer-deps

      # Step 4: Build the project (ensure "build" script exists in package.json)
      - run: npm run build

      # Step 5: Run tests (ensure "test" script exists in package.json)
      - run: npm test

